version: '3.3'

networks: 
  ntalphash:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24

services:
  mysql:
    build:
      context: .
    image: mysql:5.7.24
    restart: unless-stopped
<<<<<<< HEAD
    container_name: mysqlsrv_employees
    volumes: 
      - data-volume:/var/lib/mysql
    networks: 
        ntalphash:
          ipv4_address: 172.20.0.2
    ports:
      - target: 3306
        published: 3391
=======
    container_name: mysqlsrv
    volumes: 
      - data-volume:/var/lib/mysql
    networks: 
        ntalphash:
          ipv4_address: 172.20.0.2
    ports:
      - target: 3306
        published: 3392
>>>>>>> branch 'fila2' of https://github.com/gawielgo/testWebService.git
        protocol: tcp
        mode: host
    environment:
      - MYSQL_ROOT_PASSWORD=123Stella

volumes:
  data-volume:
